### ISSUE TITLE
CityMapData Not being imported completely.

### ISSUE THREAD

**Issue by Rogueit** [sacah/foe-city-layout#1]
The unlocked areas look to be importing fine but much of my city isn't coming over in the JSON import. Imported JSON seems to be the proper format based on online json validator.

**Comment by sacah** [comment]
Can you paste the map & city data into https://pastebin.com/ and send me the URLs so I can debug?

**Comment by Rogueit** [comment]
More buildings are starting to populate, but there are a few that are still missing.
https://pastebin.com/urCs5cHH

**Comment by xylolyx** [comment]
same here... 
https://pastebin.com/hLzwRR7S

**Comment by sacah** [comment]
I was missing the new buildings for this event and SAAB, have imported latest data.
Rogueit, xylolyx, can you try again please, both your datas worked for me.

**Comment by xylolyx** [comment]
works excellent again... :-D 👍👍👍

**Comment by Rogueit** [comment]
yup...that looks good...thanks man!

**Comment by Rogueit** [comment]
latest data import seems to clear up the issue
