### ISSUE TITLE
Unknown buildings stops rendering of city.

### ISSUE THREAD

**Issue by NickRing** [sacah/foe-city-layout#2]
The following buildings are unknown.

"A_MultiAge_SportBonus17b"
"L_AllAge_Expedition16Small"
"R_MultiAge_SummerBonus20i"
"V_IndustrialAge_Harbor"
"V_IronAge_GuildExpedition"

**Comment by sacah** [comment]
This should be fixed now, imported the latest data. I didn't think anyone used this now a very similar tool has been added to FOE Helper.
If it's not fixed, can you paste your cities import data into pastebins or something and let me know so I can test with them please.

**Comment by NickRing** [comment]
FOE Helper needs you have to an account...  I prefer this over having to set up another account.

And the city imported without issue. Thank you
