### ISSUE TITLE
Suggestion to use FoE Helper Copy city data format as input

### ISSUE THREAD

**Issue by WulfgarCA** [sacah/foe-city-layout#3]
Hi, 
I like your approach to the city planer but I think the Import feature can be enhanced now, since the newest version of the foe helper has a copy city data feature, which copies both JSON.stringify(CityMap.UnlockedAreas) and JSON.stringify(MainParser.CityMapData) to the clipboard at the same time.
If you could change your input screen to accept the combine format, than it would be much easier for people to use your cityplaner without using the console.
Also and update to the buildings to include the new event buildings would be great!

**Comment by sacah** [comment]
Hey,
So I have updated the building data, but the 'Copy citymap data' button in the 'Your city' dialog doesn't work for me, it takes a few seconds, says 'Your city data is now in the clipboard', but it's not. I just assumed it's not working for anyone. I'm using FoEHelper v2.5.6.3 on Chrome, what are you using?

**Comment by WulfgarCA** [comment]
With Chrome its not very performaned yet, it times out quite often or takes like 90 seconds. Firefox works much better! Thanks for updating!

**Comment by sacah** [comment]
Nice, FF is my daily driver, but I leave the game open in Chrome. I've updated so the first box can also accept the citymap data from FoE helper.

**Comment by WulfgarCA** [comment]
Works like a charm! Thank you so much!
