### ISSUE TITLE
Import of city data has extra quoting

### ISSUE THREAD

**Issue by udalrich** [sacah/foe-city-layout#6]
When I copy the content of `JSON.stringify(MainParser.CityMapData)` to https://sacah.github.io/foe-city-layout/, there is extra quoting:

```
{\"__class__\":\"IdleState\"},\"__class__\":\"CityMapEntity\"},\"2000000005\":
```
This leads to errors parsing the content:

> Uncaught SyntaxError: Unexpected token x in JSON at position 1
    at JSON.parse (<anonymous>)
    at HTMLButtonElement.<anonymous> (main.js:53)
(anonymous) @ main.js:53
11:34:53.640 

> DevTools failed to load SourceMap: Could not load content for https://sacah.github.io/foe-city-layout/libs/interact/interact.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I am using Chrome Version 90.0.4430.212 (Official Build) (64-bit) on Windows 10 Home

**Comment by sacah** [comment]
In FoE Helper, can you try going into Town Overview->Copy citymap data, and paste that into the first box.
It looks like FoE Helper have committed their clipboard fix, so it will work in Chrome now. If it works for you, I'll remove the option to do the 2 JSON.stringify commands, and just get people to use FoE Helpers Town Overview.

**Comment by sacah** [comment]
@udalrich did the Copy citymap data work for you?

**Comment by udalrich** [comment]
It seems to have.  The submit button in the game works now, and I didn't
have to do the copy/paste from the developers console.

**Comment by sacah** [comment]
So that will submit to FoE helpers tool, not this one. If you are happy logging in and using that tool, awesome. This site is an older one, before that tool was released, and is mainly used by people who don't want to login.
I'll close this one, and update my tool to only use FoE copy city map data.
