### ISSUE TITLE
Allow multi-select for movement

### ISSUE THREAD

**Issue by geoffbon** [sacah/foe-city-layout#7]
So great to see some of the recent changes.  

One thing which would make things easier is being able to multi-select, either by an initial click to select, then shift-click (or ctrl-click) to select each subsequent building.  You already have a pulsing glow around the selected item, so the idea that we can select something and then do something else makes it look a bit like you're already planning this (in which case, great!).

Even better would be a selection marquee, but I'm not sure whether that's a really big change in comparison.

Regardless, once multiple items are selected, they could be all dragged together to a new location (or into the storage panel on the left).

**Comment by sacah** [comment]
Hey,
The library I use for dragging doesn't have the option, but I've hacked something together that seems to get the job done.
As I already have Ctrl + Click to delete buildings I added Alt + Click to select/deselect.

Hope it helps.

**Comment by geoffbon** [comment]
Great to hear - I'm guessing it's not deployed yet?  Neither ctrl-click or alt-click seem to do anything other than a normal selection at the moment.

**Comment by sacah** [comment]
Wondering if you have confused my tool with FoE Helpers City Layout tool? My tool is hosted at https://sacah.github.io/foe-city-layout/
It's a fairly simple layout tool that I created before FoE Helper had one, I just maintain it now for people who don't want to have to login to FoE Helper to use a city layout tool (-:

**Comment by geoffbon** [comment]
You're dead right! My apologies, and now that I try your tool, it does feel lighter, so I'm definietly going to experiment with it.
I did notice that when I multi-select then drag, the items being dragged don't move in sync - they move at different speeds, meaning they end up separated relative to one another.
