### ISSUE TITLE
New Era

### ISSUE THREAD

**Issue by WulfgarCA** [sacah/foe-city-layout#8]
Hi there,
can you please update for the new era and buildings?

Thanks
Sascha

P.S.: I will try to update myself, but i am not sure if your instruction is only for new buildings or also new era.

**Comment by sacah** [comment]
Will do, I'm automating much of the process, but it's not quite ready yet, will do manually for now.

**Comment by sacah** [comment]
The latest buildings are there, can you let me know 1 building from the new era that isn't there and I can look into it.

**Comment by WulfgarCA** [comment]
Thanks for the quick reply! All buildings do show up now!
The Only problem I have found so far are:
Golden Orrey Lvl 10 shows up at 1x1
Stage of Ages shows up at 1x1

So not sure what wen wron. Also if I add both building in the tool, they come up as 1x1.

**Comment by WulfgarCA** [comment]
i just checked:
https://github.com/sacah/foe-city-layout/blob/master/src/data/buildingInfo.js

and the buildings dont have a width and hight entry.....

Buildings ID: 1516-1530 all are missing the hight and width parameter

**Comment by sacah** [comment]
Seems those have size defined differently, I've finally got around to finishing the auto-updater, and it handles those, hopefully all saves carry over successfully too.
